language: php
php:
    - '7.1'
    - hhvm
    - nightly

before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction --dev
    - chmod +x ./vendor/overtrue/phplint/bin/phplint

script:
    - ./vendor/bin/phplint
    - phpunit
