language: php
php:
    - '7.1'
    - hhvm
    - nightly

before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction --dev
    - chmod +x ./vendor/bin/*

script:
    - ./vendor/bin/phplint
    - ./vendor/bin/phpcs --colors --standard=PSR2 src
    - phpunit
